online_claims/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
]

website/urls.py
from django.urls import path

from . import views

app_name = "website"

urlpatterns = [
    path('', views.home, name="home"),
    path('submit-claim', views.submit_claim, name='submit_claim'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    template = "website/index.html"
    return render(request, template)

def submit_claim(request):
    template = "website/submit_claim.html"
    return render(request, template)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
    <link href="{%static 'css/styles.css' %}" rel="stylesheet">
  </head>
        <body>
          <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
              <a class="navbar-brand" href="#">Re-Claim</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'website:home' %}">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Services</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#">Contacts</a>
                  </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
              </div>
            </nav>
          </header>

          <main role="main">

              {% block content %}
              {% endblock %}

          </main>

          <footer class="text-muted">
            <div class="container">
              <p class="float-right">
                <a href="#">Back to top</a>
              </p>
              <p>Re-Claim is &copy; 2019</p>
            </div>
          </footer>

          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
          <script src="{% static 'js/custom.js' %}"></script>
    </body>
</html>

website/templates/website/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="jumbotron text-center hero-section">
  <div class="container">
    <h1 class="jumbotron-heading">Welcome to Re-Claim</h1>
    <p class="lead">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <a href="{% url 'website:submit_claim' %}" class="btn btn-primary my-2">Submit Claim</a>
      <a href="#" class="btn btn-secondary my-2">About Us</a>
    </p>
  </div>
</section>

<section id="aboutus" class="about-us">
  <div class="container">
    <h3 class="section-heading">About <span class="slim-heading">Us</span></h3>
    <div class="row">
      <div class="col-md-7">
        <div class="about-text">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisl libero, maximus vitae tellus pharetra, ultricies accumsan nisi. Praesent ut laoreet est. Ut porttitor dapibus porttitor. Ut pulvinar tellus eu dolor placerat mattis id nec tellus. Mauris ac lectus feugiat, ultrices augue id, commodo ante. Praesent leo leo, interdum feugiat sollicitudin vitae, auctor non velit. Pellentesque consectetur posuere turpis, quis dictum felis mattis vel. Nullam vestibulum in velit sit amet dictum. Mauris luctus elit nec quam mattis ultricies non eu lacus.
          </p>
        </div>
      </div>
      <div class="col-md-5">
        <div class="about-img">
          <img class="img-fluid" src="{% static 'img/about-us1.jpg' %}">
        </div>
      </div>
    </div>
  </div>
</section>

<section class="album py-5 bg-light testimonials">
  <div class="container">
    <h3 class="section-heading">What Our <span class="slim-heading">Clients Say</span></h3>
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          <div class="card-body">
            <h4>John Doe</h4>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>

          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          <div class="card-body">
            <h4>Jane Doe</h4>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>

          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          <div class="card-body">
            <h4>Jack Frost</h4>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

website/templates/website/submit_claim.html
{% extends "base.html" %}

{% block title %}Submit Claim{% endblock %}

{% block content %}
<section id="claimform" class="claimform">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="claim-form">
                    <div class="form-group">
                         <label for="customer-name">Customer/Proposer Name</label>
                         <input type="text" name="proposer_name" class="form-control" placeholder="E.g. John Doe">
                    </div>
                    <div class="form-group">
                         <label for="customer-name">ID/Passport No</label>
                         <input type="text" name="proposer_name" class="form-control" placeholder="E.g. 28801345">
                    </div>
                    <div class="form-group">
                         <label for="customer-name">PIN No</label>
                         <input type="text" name="proposer_name" class="form-control" placeholder="E.g. A003456754">
                    </div>
                </div>
            </div>
            <!-- End col -->
            <div class="col-md-6">
                <div class="claim-form">
                    <div class="form-group">
                         <label for="customer-name">Email</label>
                         <input type="email" name="proposer_email" class="form-control" placeholder="E.g. user@email.com">
                    </div>
                    <div class="form-group">
                         <label for="customer-name">Mobile No</label>
                         <input type="text" name="proposer_name" class="form-control" placeholder="E.g. +25471234567890">
                    </div>
                    <div class="form-group">
                         <label for="customer-name">Customer/Proposer Name</label>
                         <input type="text" name="proposer_name" class="form-control" placeholder="E.g. John Doe">
                    </div>
                </div>
            </div>
            <!-- End col -->
      </div>
      <!-- End row -->

      <!-- Vehicle details -->
      <div class="row">
          <div class="col-md-4">
              <div class="claim-form">
                  <div class="form-group">
                      <p>Vehicle Type</p>
                      <label class="radio-inline">
                        <input type="radio" name="optradio"> Motorcycle PSV
                      </label>
                      <label class="radio-inline">
                        <input type="radio" name="optradio"> Tuk Tuk
                      </label>
                      <label class="radio-inline">
                        <input type="radio" name="optradio"> Private Hire
                      </label>
                      <label class="radio-inline">
                        <input type="radio" name="optradio"> Taxi
                      </label>
                   </div>
                   <div class="form-group">
                       <label for="">Make</label>
                       <input type="text" name="" class="form-control" placeholder="E.g. Suzuki, Honda">
                    </div>
                    <div class="form-group">
                        <label for="">Body type</label>
                        <input type="text" name="" class="form-control" placeholder="E.g. SUV, Saloon">
                    </div>
                    <div class="form-group">
                        <label for="">Year of make</label>
                        <input type="text" name="" class="form-control" placeholder="E.g. 2000, 2018">
                    </div>
              </div>
            </div>
            <!-- Col end -->
            <div class="col-md-4">
                <div class="claim-form">
                    <div class="form-group">
                      <label for="">Color</label>
                      <input type="text" class="form-control" name="optradio" placeholder="E.g. Red, Blue">
                    </div>
                    <div class="form-group">
                      <label for="">Seating Capacity</label>
                      <input type="text" name="" class="form-control" placeholder="E.g. 2, 5, 7, 10">
                    </div>
                    <div class="form-group">
                      <label for="">Chasis No</label>
                      <input type="text" name="" class="form-control" placeholder="Chasis Number">
                    </div>
                    <div class="form-group">
                      <label for="">Engine No</label>
                      <input type="text" name="" class="form-control" placeholder="Engine Number">
                    </div>
                </div>
            </div>
            <!-- Col end -->
            <div class="col-md-4">
                <div class="claim-form">
                    <div class="form-group">
                      <label for="">Cubic capacity</label>
                      <input type="text" class="form-control" name="optradio" placeholder="">
                    </div>
                    <div class="form-group">
                      <label for="">Scope of cover</label>
                      <select class="form-control" name="" id="scope-of-cover" onchange="return scopeOfCover();">
                        <option disabled selected value="">--Select insurance scope--</option>
                        <option value="Comprehensive">Comprehensive</option>
                        <option value="TPF&T">TPF&T</option>
                        <option value="TPO">TPO</option>
                      </select>
                    </div>
                    <div class="form-group" id="vehicle-value" style="display: none;">
                      <label for="">Vehicle value</label>
                      <input type="text" name="" class="form-control" placeholder="">
                    </div>
                    <div class="form-group" id="windscreen-value" style="display: none;">
                      <label for="">Windscreen value</label>
                      <input type="text" name="" class="form-control" placeholder="">
                    </div>
                    <div class="form-group" id="sound-value" style="display: none;">
                      <label for="">Sound value</label>
                      <input type="text" name="" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                      <label for="">Use of motor vehicle</label>
                      <input type="text" name="" class="form-control" placeholder="What is the vehicle used for?">
                    </div>
                    <div class="form-group">
                      <label for="">Motor vehicle garage</label>
                      <input type="text" name="" class="form-control" placeholder="Which garage is the vehicle under?">
                    </div>
                </div>
            </div>
            <!-- Col end -->
        </div>
        <!-- End row -->
        <div class="row">
            <div class="col-md-12">
                <div class="claim-form">
                    <div class="form-group">
                      <p>Have you been involved in a vehicle accident(s) or theft whilst handling any motor vehicle in the last one year?</p>
                      <label class="radio-inline">
                        <input type="radio" name="optradio" id="incident-yes" value="Yes" onchange="return incidentsCheck();"> Yes
                      </label>
                      <label class="radio-inline">
                        <input type="radio" name="optradio" id="incident-no" value="No" onchange="return incidentsCheck();"> No
                      </label>
                    </div>
                    <div class="form-group" id="incident-detail" style="display: none;">
                      <label for="">Give details of the incident</label>
                      <textarea name="name" rows="8" cols="80" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                      <label for="">Name of previous insurer</label>
                      <input type="text" name="" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                      <label for="">Name of registered owner of this vehicle</label>
                      <input type="text" name="" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                      <p>Is interest of any financier to be noted on this policy?</p>
                      <label class="radio-inline">
                        <input type="radio" name="optradio" id="financier-yes" onchange="return financierInterest();"> Yes
                      </label>
                      <label class="radio-inline">
                        <input type="radio" name="optradio" id="financier-no" onchange="return financierInterest();"> No
                      </label>
                    </div>
                    <div class="form-group" id="financier-name" style="display: none;">
                      <label for="">Name of financier</label>
                      <input type="text" class="form-control" name="" value="">
                    </div>
                </div>
            </div>
              <!-- Col end -->
        </div>
        <!-- End row -->
    </div>
    <!-- End container -->

</section>
{% endblock %}